// vue/src/App.vue
<script setup lang="ts">
import { computed, ref, onMounted, watch } from "vue";
import { useRouter, useRoute } from "vue-router";
import { useAuthStore } from "./stores/auth";
import { useCurrentUser } from "./composables/useCurrentUser";
import { queryClient } from "./queryClient";
import GlobalSpinner from "./components/GlobalSpinner.vue";
import ToastHost from "./components/ToastHost.vue";

const auth = useAuthStore();
const router = useRouter();
const route = useRoute();
const userQuery = useCurrentUser();

const currentUser = computed(() => userQuery.data.value ?? null);
const hydrated = ref(false);
const menuOpen = ref(false);

onMounted(() => {
  hydrated.value = true;
});

// Close mobile menu on any navigation
watch(() => route.path, () => {
  menuOpen.value = false;
});

function logout() {
  auth.logout();
  queryClient.clear();
  router.push("/login");
}
</script>

<template>
  <GlobalSpinner />
  <div class="min-h-screen bg-slate-50">
    <header class="border-b border-slate-200 bg-white">
      <div class="mx-auto flex max-w-4xl items-center justify-between p-4">
        <RouterLink to="/" class="flex items-center gap-2 text-xl font-bold text-slate-900">
          <img src="/icons/icon-96x96.png" alt="" aria-hidden="true" class="h-8 w-8" />
          <span class="sr-only sm:not-sr-only">Task Manager</span>
        </RouterLink>

        <!-- Desktop nav -->
        <nav aria-label="Main Navigation" class="hidden sm:block">
          <ul class="flex items-center gap-4 text-sm text-slate-600">
            <li>
              <RouterLink to="/" exact-active-class="font-medium text-indigo-600" active-class="">Home</RouterLink>
            </li>
            <li>
              <RouterLink to="/about" active-class="font-medium text-indigo-600">About</RouterLink>
            </li>
            <template v-if="hydrated && currentUser">
              <li>
                <RouterLink to="/tasks" active-class="font-medium text-indigo-600">Tasks</RouterLink>
              </li>
              <li>
                <RouterLink to="/library" active-class="font-medium text-indigo-600">Library</RouterLink>
              </li>
              <li v-if="auth.isAdmin">
                <RouterLink to="/admin" active-class="font-medium text-indigo-600">Admin</RouterLink>
              </li>
              <li><span class="text-slate-500">{{ currentUser.email }}</span></li>
              <li>
                <button class="text-slate-600 hover:text-slate-900" @click="logout">Log out</button>
              </li>
            </template>
            <template v-else>
              <li>
                <RouterLink to="/login" active-class="font-medium text-indigo-600">Log in</RouterLink>
              </li>
              <li>
                <RouterLink to="/register" active-class="font-medium text-indigo-600">Register</RouterLink>
              </li>
            </template>
          </ul>
        </nav>

        <!-- Hamburger button (mobile only) -->
        <button
          class="sm:hidden rounded-md p-1.5 text-slate-600 hover:bg-slate-100 hover:text-slate-900"
          :aria-expanded="menuOpen"
          aria-label="Toggle navigation"
          aria-controls="mobile-menu"
          @click="menuOpen = !menuOpen"
        >
          <svg v-if="menuOpen" xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
          <svg v-else xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>

      <!-- Mobile menu -->
      <nav v-if="menuOpen" id="mobile-menu" aria-label="Mobile Navigation" class="sm:hidden border-t border-slate-200">
        <ul class="flex flex-col gap-1 px-4 py-3 text-sm text-slate-600">
          <li>
            <RouterLink to="/" exact-active-class="font-medium text-indigo-600" active-class="" class="block rounded-md px-2 py-2 hover:bg-slate-50">Home</RouterLink>
          </li>
          <li>
            <RouterLink to="/about" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">About</RouterLink>
          </li>
          <template v-if="hydrated && currentUser">
            <li>
              <RouterLink to="/tasks" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">Tasks</RouterLink>
            </li>
            <li>
              <RouterLink to="/library" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">Library</RouterLink>
            </li>
            <li v-if="auth.isAdmin">
              <RouterLink to="/admin" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">Admin</RouterLink>
            </li>
            <li class="mt-2 border-t border-slate-100 pt-2">
              <span class="block px-2 py-1 text-xs text-slate-400">{{ currentUser.email }}</span>
            </li>
            <li>
              <button class="block w-full rounded-md px-2 py-2 text-left hover:bg-slate-50" @click="logout">Log out</button>
            </li>
          </template>
          <template v-else>
            <li>
              <RouterLink to="/login" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">Log in</RouterLink>
            </li>
            <li>
              <RouterLink to="/register" active-class="font-medium text-indigo-600" class="block rounded-md px-2 py-2 hover:bg-slate-50">Register</RouterLink>
            </li>
          </template>
        </ul>
      </nav>
    </header>

    <main>
      <RouterView />
    </main>
  </div>
  <ToastHost />
</template>

// angular/src/app/app.component.ts
import { afterNextRender, Component, computed, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { SwUpdate, VersionReadyEvent } from '@angular/service-worker';
import { filter } from 'rxjs/operators';

import { AuthService } from './core/auth.service';
import { ConnectivityService } from './core/connectivity.service';
import { OfflineQueueService } from './core/offline-queue.service';
import { SnackbarComponent } from './core/snackbar.component';
import { SpinnerComponent } from './core/spinner.component';
import { ToastHostComponent } from './core/toas-host.component';
import { LibraryStore } from './library/library.store';
import { TaskStore } from './tasks/task.store';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterOutlet,
    RouterLink,
    SpinnerComponent,
    ToastHostComponent,
    RouterLinkActive,
    SnackbarComponent,
  ],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
})
export class AppComponent {
  private auth = inject(AuthService);
  private router = inject(Router);
  // each store's onInit hook is wired up before any offline -> online transitions happen.
  private taskStore = inject(TaskStore);
  private libraryStore = inject(LibraryStore);
  private swUpdate = inject(SwUpdate);

  protected readonly connectivity = inject(ConnectivityService);
  protected readonly offlineQueue = inject(OfflineQueueService);

  protected readonly currentUser = this.auth.currentUser;
  protected readonly isLoggedIn = this.auth.isLoggedIn;
  protected readonly isAdmin = this.auth.isAdmin;

  protected readonly hydrated = signal(false);
  protected readonly syncing = computed(
    () => this.taskStore.flushing() || this.libraryStore.flushing(),
  );
  protected readonly updateAvailable = signal(false);
  protected readonly menuOpen = signal(false);

  constructor() {
    afterNextRender(() => this.hydrated.set(true));

    // Close mobile menu on any navigation
    this.router.events
      .pipe(
        filter((e) => e instanceof NavigationEnd),
        takeUntilDestroyed(),
      )
      .subscribe(() => this.menuOpen.set(false));

    // Listen for a new SW version becoming ready and surface the snackbar.
    // isEnabled is false in dev mode (SW is disabled), so this is a no-op locally.
    if (this.swUpdate.isEnabled) {
      this.swUpdate.versionUpdates
        .pipe(
          filter((e): e is VersionReadyEvent => e.type === 'VERSION_READY'),
          takeUntilDestroyed(),
        )
        .subscribe(() => this.updateAvailable.set(true));
    }
  }

  logout(): void {
    this.auth.logout();
    this.router.navigate(['/login']);
  }

  protected reloadApp(): void {
    window.location.reload();
  }
}

<app-spinner />
<div class="min-h-screen bg-slate-50">
  <header class="border-b border-slate-200 bg-white">
    <div class="mx-auto flex max-w-4xl items-center justify-between p-4">
      <a routerLink="/" class="flex items-center gap-2 text-xl font-bold text-slate-900">
        <img src="icons/icon-96x96.png" alt="" aria-hidden="true" class="h-8 w-8" />
        <span class="sr-only sm:not-sr-only">Task Manager</span>
      </a>

      <!-- Desktop nav -->
      <nav aria-label="Main Navigation" class="hidden sm:block">
        <ul class="flex items-center gap-4 text-sm text-slate-600">
          <li>
            <a
              routerLink="/"
              routerLinkActive="font-medium text-indigo-600"
              [routerLinkActiveOptions]="{ exact: true }"
              ariaCurrentWhenActive="page"
              >Home</a
            >
          </li>
          <li>
            <a
              ariaCurrentWhenActive="page"
              routerLink="/about"
              routerLinkActive="font-medium text-indigo-600"
              >About</a
            >
          </li>
          @if (hydrated() && isLoggedIn()) {
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/tasks"
                routerLinkActive="font-medium text-indigo-600"
                class="flex items-center gap-1"
              >
                Tasks
                @if (offlineQueue.taskCount() > 0) {
                  <span
                    class="rounded-full bg-amber-400 px-1.5 py-0.5 text-xs font-medium text-white"
                  >
                    {{ offlineQueue.taskCount() }}
                  </span>
                }
              </a>
            </li>
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/library"
                routerLinkActive="font-medium text-indigo-600"
                class="flex items-center gap-1"
              >
                Library
                @if (offlineQueue.libraryCount() > 0) {
                  <span
                    class="rounded-full bg-amber-400 px-1.5 py-0.5 text-xs font-medium text-white"
                  >
                    {{ offlineQueue.libraryCount() }}
                  </span>
                }
              </a>
            </li>
            @if (isAdmin()) {
              <li>
                <a
                  ariaCurrentWhenActive="page"
                  routerLink="/admin"
                  routerLinkActive="font-medium text-indigo-600"
                  >Admin</a
                >
              </li>
            }
            <li>
              <span class="text-slate-500">{{ currentUser()?.email }}</span>
            </li>
            <li>
              <button (click)="logout()" class="text-slate-600 hover:text-slate-900">
                Log out
              </button>
            </li>
          } @else {
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/login"
                routerLinkActive="font-medium text-indigo-600"
                >Log in</a
              >
            </li>
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/register"
                routerLinkActive="font-medium text-indigo-600"
                >Register</a
              >
            </li>
          }
        </ul>
      </nav>

      <!-- Hamburger button (mobile only) -->
      <button
        (click)="menuOpen.set(!menuOpen())"
        class="sm:hidden rounded-md p-1.5 text-slate-600 hover:bg-slate-100 hover:text-slate-900"
        [attr.aria-expanded]="menuOpen()"
        aria-label="Toggle navigation"
        aria-controls="mobile-menu"
      >
        @if (menuOpen()) {
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        } @else {
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            stroke-width="2"
          >
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        }
      </button>
    </div>

    <!-- Mobile menu -->
    @if (menuOpen()) {
      <nav
        id="mobile-menu"
        aria-label="Mobile Navigation"
        class="sm:hidden border-t border-slate-200"
      >
        <ul class="flex flex-col gap-1 px-4 py-3 text-sm text-slate-600">
          <li>
            <a
              routerLink="/"
              routerLinkActive="font-medium text-indigo-600"
              [routerLinkActiveOptions]="{ exact: true }"
              ariaCurrentWhenActive="page"
              class="block rounded-md px-2 py-2 hover:bg-slate-50"
              >Home</a
            >
          </li>
          <li>
            <a
              ariaCurrentWhenActive="page"
              routerLink="/about"
              routerLinkActive="font-medium text-indigo-600"
              class="block rounded-md px-2 py-2 hover:bg-slate-50"
              >About</a
            >
          </li>
          @if (hydrated() && isLoggedIn()) {
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/tasks"
                routerLinkActive="font-medium text-indigo-600"
                class="flex items-center gap-1.5 rounded-md px-2 py-2 hover:bg-slate-50"
              >
                Tasks
                @if (offlineQueue.taskCount() > 0) {
                  <span
                    class="rounded-full bg-amber-400 px-1.5 py-0.5 text-xs font-medium text-white"
                  >
                    {{ offlineQueue.taskCount() }}
                  </span>
                }
              </a>
            </li>
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/library"
                routerLinkActive="font-medium text-indigo-600"
                class="flex items-center gap-1.5 rounded-md px-2 py-2 hover:bg-slate-50"
              >
                Library
                @if (offlineQueue.libraryCount() > 0) {
                  <span
                    class="rounded-full bg-amber-400 px-1.5 py-0.5 text-xs font-medium text-white"
                  >
                    {{ offlineQueue.libraryCount() }}
                  </span>
                }
              </a>
            </li>
            @if (isAdmin()) {
              <li>
                <a
                  ariaCurrentWhenActive="page"
                  routerLink="/admin"
                  routerLinkActive="font-medium text-indigo-600"
                  class="block rounded-md px-2 py-2 hover:bg-slate-50"
                  >Admin</a
                >
              </li>
            }
            <li class="mt-2 border-t border-slate-100 pt-2">
              <span class="block px-2 py-1 text-xs text-slate-400">{{ currentUser()?.email }}</span>
            </li>
            <li>
              <button
                (click)="logout()"
                class="block w-full rounded-md px-2 py-2 text-left hover:bg-slate-50"
              >
                Log out
              </button>
            </li>
          } @else {
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/login"
                routerLinkActive="font-medium text-indigo-600"
                class="block rounded-md px-2 py-2 hover:bg-slate-50"
                >Log in</a
              >
            </li>
            <li>
              <a
                ariaCurrentWhenActive="page"
                routerLink="/register"
                routerLinkActive="font-medium text-indigo-600"
                class="block rounded-md px-2 py-2 hover:bg-slate-50"
                >Register</a
              >
            </li>
          }
        </ul>
      </nav>
    }
  </header>

  @if (connectivity.offline()) {
    <div
      role="status"
      class="flex items-center justify-center gap-2 border-b border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-800"
    >
      <span>You're offline</span>
      @if (offlineQueue.totalPending() > 0) {
        <span class="rounded-full bg-amber-200 px-2 py-0.5 text-xs font-medium">
          {{ offlineQueue.totalPending() }} change{{ offlineQueue.totalPending() === 1 ? '' : 's' }}
          pending
        </span>
      }
    </div>
  } @else if (syncing()) {
    <div
      role="status"
      class="flex items-center justify-center gap-2 border-b border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800"
    >
      <span>Syncing changes...</span>
    </div>
  }

  <main>
    <router-outlet />
  </main>
</div>
<app-toast-host />

@if (updateAvailable()) {
  <app-snackbar
    message="A new version is available"
    action="Reload"
    (actionClick)="reloadApp()"
    (dismissed)="updateAvailable.set(false)"
  />
}
